--- 
title: "Categorical Models"
author: "Michael Clark"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
    bookdown::tufte_html_book:
      toc: yes
      css: [toc.css, style_for_miles_and_miles_so_much_style_that_its_wasted.css]
      highlight: pygments
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: repohere
description: "description"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, cache=F, message = F, warnings=F, 
                      R.options=list(width=120), fig.align='center')
```
```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```

```{r echo=FALSE}
library(tufte); library(tidyverse); library(lazerhawk)
```



# Preface

This work will be added to, corrected, etc. but has enough content for now to make available.

Bookdown is broken $f(k) = {n \choose k} p^{k} (1-p)^{n-k}$

Color coding:

- <span class="emph">emphasis</span>
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object/class</span>
- [link]()
